name: Process Projects JSON

on:
  push:
    paths:
      - projects.json

jobs:
  process-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read and process projects.json
        run: |
          JSON_FILE="projects.json"
          if [[ -f "$JSON_FILE" ]]; then
            echo "Processing $JSON_FILE"
            cat $JSON_FILE | jq -r '.projects[] | "\(.name) \(.repositories[] | "\(.name): \(.url)")"' > project-repos.txt
            cat project-repos.txt
          else
            echo "$JSON_FILE not found!"
            exit 1
          fi
