name: Get Repositories

on:
  workflow_dispatch:
  #push:
    #paths:
      #- Projects.json

jobs:
 Install_gh_CLI:
     runs-on: ubuntu-latest
     steps:
      - name: Install gh CLI
        run: |
          # Install gh CLI
          sudo mkdir -p -m 755 /etc/apt/keyrings && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

 process-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read and process projects.json
        id: process_json
        run: |
          FILE_PATH="Projects.json"
          if [[ -f "$FILE_PATH" ]]; then
            echo "Processing $FILE_PATH"
            cat $FILE_PATH | jq -r '.projects[] | "\(.name) \(.repositories[] | "\(.name): \(.url)")"' > project-repos.txt
          else
            echo "$FILE_PATH not found!"
          fi

      
 print-projects:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print Projects, Repository Names and URLs
      run: |
        cat Projects.json | jq -r '.projects[] | "\(.name): \(.repositories[].name) - \(.repositories[].url)"' | sort -u
      shell: bash
